package com.example.khind

var PREFERENCE_NAME = "MY_APP_PREF"
var LOGGED_IN =  "LOGGED IN"
var USERNAME = "USERNAME"
var PASSWORD = "PASSWORD"
var TOKEN = "TOKEN"
var REFRESH_TOKEN = "REFRESH_TOKEN"
var SENSOR_ID = "SENSOR_ID"
var ALARM = "ALARM"
var LONGITUDE = "LONGITUDE"
var LATITUDE = "LATITUDE"
